"""
Color bridge — LUT application, color grading, cinematic look.
Wraps ffmpeg color filters and .cube LUT files.
"""
import subprocess
import os
import logging
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger("ColorBridge")


@dataclass
class GradeResult:
    success: bool
    output_path: str
    message: str


class ColorBridge:
    """
    Color grading via ffmpeg: programmatic colorlevels or .cube LUT files.
    Maven-Edit default: contrast +8, saturation -5, gamma 0.9
    """

    def __init__(self, workspace: str = "/home/muhammad_tayyab/bootlogix/production/output"):
        self.workspace = workspace
        self.ffmpeg = self._find_ffmpeg()

    def _find_ffmpeg(self) -> str:
        try:
            return subprocess.check_output(["which", "ffmpeg"]).decode().strip()
        except subprocess.CalledProcessError:
            return "/usr/bin/ffmpeg"

    def apply_lut(
        self,
        video_path: str,
        project_id: str,
        lut_file: str
    ) -> GradeResult:
        """Apply a .cube LUT file via ffmpeg lut3d filter."""
        if not os.path.exists(video_path):
            return GradeResult(False, "", "Video not found")
        if not os.path.exists(lut_file):
            return GradeResult(False, "", f"LUT not found: {lut_file}")

        project_dir = os.path.join(self.workspace, project_id)
        os.makedirs(project_dir, exist_ok=True)
        output_path = os.path.join(project_dir, "graded_lut.mp4")

        cmd = [
            self.ffmpeg, "-y", "-i", video_path,
            "-vf", f"lut3d={lut_file}",
            "-c:v", "libx264", "-preset", "fast", "-crf", "18",
            "-c:a", "copy",
            output_path
        ]

        try:
            subprocess.run(cmd, capture_output=True, check=True)
            return GradeResult(True, output_path, f"LUT applied: {os.path.basename(lut_file)}")
        except subprocess.CalledProcessError as e:
            return GradeResult(False, "", f"LUT apply failed: {e.stderr}")

    def apply_cinematic_grade(
        self,
        video_path: str,
        project_id: str,
        contrast: float = 1.08,
        saturation: float = 0.95,
        gamma: float = 0.9,
        brightness: float = 0.0,
        output_name: str = "step2_graded.mp4"
    ) -> GradeResult:
        """
        Apply Maven-Edit cinematic color grade via ffmpeg colorlevels.
        Maven-Edit values: contrast +8%, saturation -5%, gamma 0.9
        """
        if not os.path.exists(video_path):
            return GradeResult(False, "", "Video not found")

        project_dir = os.path.join(self.workspace, project_id)
        os.makedirs(project_dir, exist_ok=True)
        output_path = os.path.join(project_dir, output_name)

        # ffmpeg 7.x: eq for contrast/saturation, colorlevels for contrast compression
        # romax=0.92 compresses whites → creates contrast effect
        filter_str = (
            f"eq=brightness={brightness}:contrast={contrast}:saturation={saturation},"
            f"colorlevels=romax={1.0/contrast:.3f}"
        )

        cmd = [
            self.ffmpeg, "-y", "-i", video_path,
            "-vf", filter_str,
            "-c:v", "libx264", "-preset", "fast", "-crf", "18",
            "-c:a", "copy",
            output_path
        ]

        try:
            subprocess.run(cmd, capture_output=True, check=True, text=True)
            return GradeResult(True, output_path, "Cinematic grade applied")
        except subprocess.CalledProcessError as e:
            logger.error(f"Cinematic grade failed: {e.stderr}")
            return GradeResult(False, "", f"Grade failed: {e.stderr}")

    def create_cube_lut(
        self,
        project_id: str,
        lut_name: str = "Cinematic_Shorts_v1",
        contrast: float = 1.08,
        saturation: float = 0.95,
        gamma: float = 0.9
    ) -> str:
        """
        Generate a .cube LUT file programmatically.
        Returns path to generated .cube file.
        """
        project_dir = os.path.join(self.workspace, project_id)
        os.makedirs(project_dir, exist_ok=True)
        lut_path = os.path.join(project_dir, f"{lut_name}.cube")

        # Generate a basic .cube LUT
        with open(lut_path, "w") as f:
            f.write(f"# Generated by Bootlogix ColorBridge\n")
            f.write(f"# {lut_name}: contrast={contrast}, sat={saturation}, gamma={gamma}\n\n")
            f.write("TITLE \"\"\n")
            f.write("LUT_3D_SIZE 17\n")
            f.write("DOMAIN_MIN 0.0 0.0 0.0\n")
            f.write("DOMAIN_MAX 1.0 1.0 1.0\n\n")

            size = 17
            for b in range(size):
                for g in range(size):
                    for r in range(size):
                        rf = r / (size - 1)
                        gf = g / (size - 1)
                        bf = b / (size - 1)

                        # Apply color transform
                        rf = min(1.0, max(0.0, rf * contrast))
                        gf = min(1.0, max(0.0, gf * contrast))
                        bf = min(1.0, max(0.0, bf * contrast))

                        # Gamma
                        rf = rf ** (1.0 / gamma)
                        gf = gf ** (1.0 / gamma)
                        bf = bf ** (1.0 / gamma)

                        # Clamp
                        rf = min(1.0, max(0.0, rf))
                        gf = min(1.0, max(0.0, gf))
                        bf = min(1.0, max(0.0, bf))

                        f.write(f"{rf:.6f} {gf:.6f} {bf:.6f}\n")

        return lut_path
